### ISSUE TITLE
Gracefully handle non-existent partials directory

### ISSUE THREAD

**Issue by james-async** [aarondl/tpl#1]
Do you still use this?  

I noticed it's just the initial commit, but thought I'd let you know about this panic that happens when the partials directory does not exist. It's an easy work around to get an empty directory. It was just something I stumbled across in first-use.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13a5858]

goroutine 1 [running]:
.../vendor/github.com/aarondl/tpl.Load.func1(0x0, 0x0, 0x0, 0x0, 0x1507d60, 0xc4201f0060, 0x20, 0x1456760)
	.../vendor/github.com/aarondl/tpl/tpl.go:66 +0x58
path/filepath.Walk(0x0, 0x0, 0xc420124900, 0xc4200a7f20, 0x0)
	/usr/local/Cellar/go/1.10.3/libexec/src/path/filepath/path.go:401 +0x6c
.../vendor/github.com/aarondl/tpl.Load(0x14af6aa, 0x5, 0x0, 0x0, 0x14b6e4a, 0xf, 0xc4200a7cb0, 0x14cacf7, 0x42, 0xc4200a3080)
	.../vendor/github.com/aarondl/tpl/tpl.go:65 +0x346```

**Comment by aarondl** [comment]
Hey there. This is only really used in the Authboss v1 sample, which is slowly going away in favor of https://github.com/volatiletech/authboss-renderer

This still remains a useful small library I think if you're trying to achieve that sort of layout + partials kind of thing. Though I think there are probably other things that do it better nowadays.

Did you find this while working with authboss? Curious what led you here :)

**Comment by aarondl** [comment]
Oh and FWIW I think I fixed it. Was able to startup the authboss sample without a partials dir with no crashes.
